Repository Billing-Wise/client, pull requests merged in 2024-07, with the labels that each got.

#1 [K5P-37] [env] Vue 프로젝트 초기 구성
  .eslintrc.cjs
  .gitignore
  .prettierrc.json
  README.md
  cypress.config.js
  cypress/e2e/example.cy.js
  cypress/e2e/jsconfig.json
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  index.html
  jsconfig.json
  package-lock.json
  package.json
  public/favicon.ico
  src/App.vue
  src/assets/fonts/DoHyeon-Regular.ttf
  src/assets/images/logo_white.png
  src/assets/images/name_white.png
  src/assets/scss/auth.scss
  src/assets/scss/common.scss
  src/assets/scss/main.scss
  src/components/auth/AuthButton.vue
  src/components/auth/AuthInput.vue
  src/components/auth/LogoSide.vue
  src/components/common/NavBar.vue
  src/components/common/SideBar.vue
  src/components/common/side-bar/SideBarItem.vue
  src/components/common/side-bar/SideBarLogout.vue
  src/main.js
  src/router/index.js
  src/stores/auth.js
  src/views/MainView.vue
  src/views/auth/AuthView.vue
  src/views/auth/CertifyView.vue
  src/views/auth/LoginView.vue
  src/views/auth/SignupView.vue
  src/views/contract/ContractListView.vue
  src/views/home/HomeView.vue
  src/views/invoice/InvoiceListView.vue
  src/views/item/ItemListView.vue
  src/views/member/MemberListView.vue
  src/views/setting/SettingView.vue
  vite.config.js
  vitest.config.js
Labels: env

#4 [release, cd] 배포 스크립트 작성
  .eslintrc.cjs
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/cd.yml
  .gitignore
  .prettierrc.json
  README.md
  cypress.config.js
  cypress/e2e/example.cy.js
  cypress/e2e/jsconfig.json
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  index.html
  jsconfig.json
  package-lock.json
  package.json
  public/favicon.ico
  src/App.vue
  src/assets/fonts/DoHyeon-Regular.ttf
  src/assets/images/logo_white.png
  src/assets/images/name_white.png
  src/assets/scss/auth/auth.scss
  src/assets/scss/common.scss
  src/assets/scss/main.scss
  src/components/auth/AuthBtnInput.vue
  src/components/auth/AuthButton.vue
  src/components/auth/AuthInput.vue
  src/components/auth/LogoSide.vue
  src/components/common/TheNavBar.vue
  src/components/common/TheSideBar.vue
  src/components/common/side-bar/SideBarItem.vue
  src/components/common/side-bar/SideBarLogout.vue
  src/main.js
  src/router/index.js
  src/stores/auth.js
  src/stores/signup.js
  src/utils/auth.js
  src/utils/axios.js
  src/views/MainView.vue
  src/views/auth/AuthView.vue
  src/views/auth/LoginView.vue
  src/views/auth/SignupView.vue
  src/views/contract/ContractListView.vue
  src/views/home/HomeView.vue
  src/views/invoice/InvoiceListView.vue
  src/views/item/ItemListView.vue
  src/views/member/MemberListView.vue
  src/views/setting/SettingView.vue
  vite.config.js
  vitest.config.js
Labels: cd, release

#5 [ci] ci 스크립트 작성
  .github/workflows/ci.yml
  sonar-project.properties
Labels: ci

#10 [feat] 납부자 결제(카드)
  src/assets/images/loading.png
  src/assets/images/success.png
  src/assets/images/warn.png
  src/components/payment/AgreementBox.vue
  src/components/payment/DescriptionBox.vue
  src/components/payment/ErrorContainer.vue
  src/components/payment/ItemContent.vue
  src/components/payment/ItemTitle.vue
  src/components/payment/LoadingContainer.vue
  src/components/payment/NextPageButton.vue
  src/components/payment/PaymentContainer.vue
  src/router/index.js
  src/stores/cardInfo.js
  src/stores/paymentInfo.js
  src/stores/paymentResult.js
  src/views/MobileView.vue
  src/views/payment/AccountPaymentAgreementView.vue
  src/views/payment/CardPaymentAgreementView.vue
  src/views/payment/CardPaymentConfirmView.vue
  src/views/payment/CardPaymentInputView.vue
  src/views/payment/PaymentInfoView.vue
  src/views/payment/PaymentMethodView.vue
  src/views/payment/PaymentResultView.vue
  src/views/payment/PaymentStartView.vue
Labels: feat

#13 [feat] 간편동의페이지
  src/assets/images/sign.png
  src/assets/images/sign0.gif
  src/assets/images/도장.png
  src/assets/images/온라인결제.png
  src/components/common/btn/ThemeBtn.vue
  src/router/index.js
  src/stores/contract.js
  src/utils/axios.js
  src/views/consent/AccountInfoView.vue
  src/views/consent/ConsentExplanationView.vue
  src/views/consent/ConsentItemView.vue
  src/views/consent/ContractInfoConfirmation.vue
  src/views/consent/ContractInfoView.vue
  src/views/consent/FinalConfirmation.vue
  src/views/consent/MemberInfoView.vue
  src/views/consent/SignatureInput.vue
Labels: feat

#14 [fix] 계약 store 충돌 해소
  src/components/contract/ContractTable.vue
  src/components/contract/table/ContractTableFilter.vue
  src/stores/contractList.js
  src/views/contract/ContractListView.vue
Labels: fix

#16 [fix, feat] 납부자 결제 css 수정 & 뒤로가기 구현
  src/assets/images/loading.gif
  src/components/payment/AgreementBox.vue
  src/components/payment/ButtonContainer.vue
  src/components/payment/ErrorContainer.vue
  src/components/payment/LoadingContainer.vue
  src/components/payment/NextPageButton.vue
  src/views/payment/PaymentInfoView.vue
  src/views/payment/PaymentMethodView.vue
  src/views/payment/PaymentResultView.vue
  src/views/payment/account/AccountPaymentAgreementView.vue
  src/views/payment/account/AccountPaymentConfirmView.vue
  src/views/payment/account/AccountPaymentInputView.vue
  src/views/payment/card/CardPaymentAgreementView.vue
  src/views/payment/card/CardPaymentConfirmView.vue
  src/views/payment/card/CardPaymentInputView.vue
Labels: feat, fix

#17 [feat] 비회원 간편동의 개발
  src/assets/images/sign.gif
  src/router/index.js
  src/stores/contract.js
  src/views/consent/AccountInfoView.vue
  src/views/consent/ContractInfoConfirmation.vue
  src/views/consent/DrawSignature.vue
  src/views/consent/FinalConfirmation.vue
  src/views/consent/MemberInfoView.vue
  src/views/consent/PaymentCompletion.vue
  src/views/consent/SignatureInput.vue
  src/views/consent/UploadSignature.vue
Labels: feat

#19 [feat] 회원 간편동의 컴포넌트 개발
  src/router/index.js
  src/stores/consent/member/consentAccountInfo.js
  src/stores/consent/member/consentContractInfo.js
  src/stores/consent/member/consentResult.js
  src/stores/consent/non-member/contract.js
  src/stores/payment/accountInfo.js
  src/stores/payment/cardInfo.js
  src/stores/payment/paymentInfo.js
  src/stores/payment/paymentResult.js
  src/views/consent/member/AccountInfoView.vue
  src/views/consent/member/ContractInfoConfirmation.vue
  src/views/consent/member/DrawSignature.vue
  src/views/consent/member/FinalConfirmation.vue
  src/views/consent/member/PaymentCompletion.vue
  src/views/consent/member/SignatureInput.vue
  src/views/consent/member/UploadSignature.vue
  src/views/consent/non-member/AccountInfoView.vue
  src/views/consent/non-member/ConsentExplanationView.vue
  src/views/consent/non-member/ConsentItemView.vue
  src/views/consent/non-member/ContractInfoConfirmation.vue
  src/views/consent/non-member/ContractInfoView.vue
  src/views/consent/non-member/DrawSignature.vue
  src/views/consent/non-member/FinalConfirmation.vue
  src/views/consent/non-member/MemberInfoView.vue
  src/views/consent/non-member/PaymentCompletion.vue
  src/views/consent/non-member/SignatureInput.vue
  src/views/consent/non-member/UploadSignature.vue
  src/views/payment/PaymentInfoView.vue
  src/views/payment/PaymentMethodView.vue
  src/views/payment/PaymentResultView.vue
  src/views/payment/account/AccountPaymentAgreementView.vue
  src/views/payment/account/AccountPaymentConfirmView.vue
  src/views/payment/account/AccountPaymentInputView.vue
  src/views/payment/card/CardPaymentAgreementView.vue
  src/views/payment/card/CardPaymentConfirmView.vue
  src/views/payment/card/CardPaymentInputView.vue
Labels: feat

#21 [feat] 간편동의 설정 컴포넌트
  src/assets/images/card-image.png
  src/assets/images/cms-image.png
  src/components/common/TheSideBar.vue
  src/components/setting/SettingItemTable.vue
  src/components/setting/SettingItemTableRow.vue
  src/components/setting/SettingPaginationBar.vue
  src/components/setting/SettingPaymentContent.vue
  src/components/setting/SettingTableHeader.vue
  src/router/index.js
  src/stores/setting/settingItem.js
  src/utils/setting.js
  src/views/setting/SettingItemView.vue
  src/views/setting/SettingPaymentView.vue
  src/views/setting/SettingView.vue
Labels: feat
